name: Publish Packages to NPM

on:
  release:
    types: [published] # GitHub リリースが公開されたときにトリガー

jobs:
  publish:
    name: Publish Monorepo Packages
    runs-on: ubuntu-latest

    steps:
      # コードをチェックアウト
      - name: Check out code
        uses: actions/checkout@v4

      # Node.js をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org/'

      # NPM 認証
      - name: Authenticate to npm
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # pnpm のインストールと依存関係の解決
      - name: Install pnpm
        run: |
          corepack enable
          pnpm install

      # 各パッケージのビルド
      - name: Build all packages
        run: pnpm build

      # 変更があるパッケージだけを NPM に公開
      - name: Publish updated packages
        run: pnpm publish -r --filter ./packages/core --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}